//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stajprojesi.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class komo
    {
        public int id { get; set; }
        public string komad { get; set; }
        public string kom { get; set; }
    }
}
