//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stajprojesi.Models.EntitiyFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stajProjesiEntities2 : DbContext
    {
        public stajProjesiEntities2()
            : base("name=stajProjesiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<komisyon> komisyon { get; set; }
        public virtual DbSet<komo> komo { get; set; }
        public virtual DbSet<konular> konular { get; set; }
        public virtual DbSet<mulakat> mulakat { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<staj> staj { get; set; }
        public virtual DbSet<stajBilgisi> stajBilgisi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
