//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stajprojesi.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mulakat
    {
        public int id { get; set; }
        public int ogr_no { get; set; }
        public string bas_tarihi { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public Nullable<int> komisyon1 { get; set; }
        public Nullable<int> komisyon2 { get; set; }
        public Nullable<int> devam { get; set; }
        public Nullable<int> caba { get; set; }
        public Nullable<int> is_vaktinde_yapma { get; set; }
        public Nullable<int> amire_davranis { get; set; }
        public Nullable<int> ekibe_davranis { get; set; }
        public Nullable<int> proje { get; set; }
        public Nullable<int> duzen { get; set; }
        public Nullable<int> sunum { get; set; }
        public Nullable<int> icerik { get; set; }
        public Nullable<int> mulakat1 { get; set; }
    }
}
