//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stajprojesi.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class stajBilgisi
    {
        public string kurum_adi { get; set; }
        public string sehir { get; set; }
        public Nullable<int> toplam_gun { get; set; }
        public string staj_konu { get; set; }
        public Nullable<int> ogr_sinif { get; set; }
        public Nullable<int> kabul_gun { get; set; }
        public Nullable<bool> durum { get; set; }
        public int ogr_no { get; set; }
        public string bas_tarihi { get; set; }
        public string bit_tarihi { get; set; }
        public int id { get; set; }
    
        public virtual ogrenci ogrenci { get; set; }
    }
}
